title = "University of Stirling Computer Club"
baseURL = "https://stirlingcomputer.club"
languageCode = "en-gb"
theme = ["github.com/lower-elements/elemental"]

[params]
shortTitle = "USCC"
description = """
We're the USCC, the University of Stirling's computing society. Join us to learn about trending technological topics,
get insight into what's popular at the moment in tech, and most of all, meet awesome people with similar interests.
"""

[params.author]
name = "USCC team"
email = "committee@stirlingcomputer.club"
url = "https://github.com/orgs/Stirling-USSC/people"

[menu]

  [[menu.main]]
  identifier = "linktree"
  name = "Links"
  weight = -10
  url = "https://linktr.ee/stirlingcomputerclub"
  [[menu.main]]
  identifier = "membership"
  name = "Buy Membership"
  weight = 0
  url = "https://www.stirlingstudentsunion.com/societies/6155/"

  [[menu.social]]
  identifier = "instagram"
  name = "Instagram (stirlingcomputerclub)"
  weight = -70
  url = "https://www.instagram.com/computerclubstirling"
  [[menu.social]]
  identifier = "github"
  name = "Github (stirling-ussc)"
  weight = -50
  url = "https://github.com/stirling-ussc"
  [[menu.social]]
  identifier = "discord"
  name = "Discord (USCC server)"
  weight = -30
  url = "https://discord.gg/DZnAvAnhKD"

[module]
    [[module.imports]]
    path = "github.com/lower-elements/elemental"
    disable=false
